version: "3.8"

services:
  roborally-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roborally-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://130.225.71.179:5100
    restart: unless-stopped
    network_mode: "host"
